return {
  'folke/todo-comments.nvim',
  dependencies = { 'nvim-lua/plenary.nvim' },
  opts = {
    signs = true,
    keywords = {
      TODO = { icon = ' ', color = 'todo' },
      FIX = { icon = ' ', color = 'error', alt = { 'FIXME', 'BUG', 'FIXIT' } },
      HACK = { icon = ' ', color = 'warning' },
      WARN = { icon = ' ', color = 'warning', alt = { 'WARNING', 'XXX' } },
      NOTE = { icon = ' ', color = 'hint', alt = { 'INFO' } },
      BL = { icon = '', color = 'blue', alt = {} },
      OR = { icon = '󰋼', color = 'info', alt = {} },
      WH = { icon = '󱆾', color = 'white', alt = {} },
      YEL = { icon = ' ', color = 'yellow', alt = {} },
      PU = { icon = '󱁯', color = 'purple', alt = {} },
      GR = { icon = '󰀭', color = 'green', alt = {} },
      PNK = { icon = '󱁯', color = 'test', alt = {} },
    },
    colors = {
      todo = '#FF8C00',
      error = '#DC2626',
      warning = '#FBBF24',
      blue = '#2563EB',
      hint = '#10B981',
      default = '#7C3AED',
      test = '#FF00FF',
      green = '#22c55e',
      white = '#FFFFFF',
      yellow = '#FFFF00',
      purple = '#BF00FF',
    },
  },
}
